### PR TITLE
Add GH action for testing

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
I saw the installation of `node` takes a long time. I'm experiencing similar behavior on my laptop (I think it was faster on my desktop computer, but it might have been long time ago and I just don't remember).

By removing `node`, build time was much faster. It's now [erroring here](https://github.com/amitaibu/ihp-landing-page/actions/runs/5360407749/jobs/9725239191#step:5:2800), which is probably outdated. I'll try to use `devenv up`

**Comment by amitaibu** [comment]
Build takes 30min, but we should add [cachix](https://nix.dev/tutorials/nixos/build-and-deploy/continuous-integration-github-actions), and I believe it would speed it up once it's cached.

For this repo we need to add RSA keys (see [error](https://github.com/amitaibu/ihp-landing-page/actions/runs/5360620319/jobs/9725711233#step:8:1629))

`ssh-keygen -t rsa -b 4096 -m PEM -f ./Config/jwtRS256.key && openssl rsa -in ./Config/jwtRS256.key -pubout -outform PEM -out ./Config/jwtRS256.key.pub`

**Comment by mpscholten** [comment]
@amitaibu the nodejs issue was also reported to me by @s0kil. It seems something is off with our current nixpkgs revision that causes nodejs to be not in the standard binary cache

**Comment by amitaibu** [comment]
`nix-shell --run "runghc $(make print-ghc-extensions) -i. -ibuild -iConfig Test/Main.hs"` seems to invoke all the tests of all the packages, Not just the custom ones. See [example](https://github.com/amitaibu/ihp-landing-page/actions/runs/5363901842/jobs/9731766032#step:8:10106)

image

**Comment by amitaibu** [comment]
I think my above assumption is wrong, and that those packages tests are running as part of the build process.
It's running even when I've commented out `nix-shell --run "runghc $(make print-ghc-extensions) -i. -ibuild -iConfig Test/Main.hs"`

image

**Comment by mpscholten** [comment]
Yes this is caused by nix building a lot of stuff. It seems you've swapped out the binary cache in your github action. To speed up the build it would be helpful to add the digitallyinduced binary cache as well (using `skipPush: true`):

```yaml
      - name: Cachix Init
        uses: cachix/cachix-action@v12
        with:
          name: digitallyinduced
          skipPush: true
```

You can have multiple cachix-actions in a single github action, so you can still keep your own cachix cache there as well

**Comment by amitaibu** [comment]
>  It seems you've swapped out the binary cache in your github action

Yeah, just playing around with it. Is there a reason for me to indeed do that, or safe to stay with DI's cachix?

**Comment by amitaibu** [comment]
Oh yeah, the last commit ran for 4m, and executed the tests! :balloon:

**Comment by mpscholten** [comment]
Great!

**Comment by amitaibu** [comment]
> It seems something is off with our current nixpkgs revision that causes nodejs to be not in the standard binary cache

We still need to figure this one.

**Pull request merged**
